# Copyright 2026 Munaf Ibrahim Khatri
# SPDX-License-Identifier: Apache-2.0
"""The pgTAP emitters: probe-and-bake flat suite (emit_flat), debug emitter, hooks and RLS guard.

Split out of the original single-module cli.py; behavior-preserving.
"""
from __future__ import annotations
import argparse, json, re, sys
import psycopg
from pglast.parser import parse_sql_json
from .astutil import _CMDS4, _TAGLINE, _TAGLINE2, _expr_cols, _is_uuid, _qlit, _split_statements, _sq, _where
from .values import CV, FOREIGN, FUTURE_EXP, INS, MV, NOBODY, RIVAL_SUB
from .catalog import _FK_SQL, _columns, _constraint_meta, _effective_grants, _exposed, all_tables
from .atoms import _check_value_set, analyze
from .probe import ProbeBaker, _probe
from .seeding import _seed_plan, _synthesize_row, _wrap_seed
from .structs import EmitContext, Observation
from .strategies import AUGMENT, CONTINUE, HANDLED, REGISTRY
from .strategies.mock import _opaque_fn_sig, _policy_bool_udfs, mock_emit
from .strategies.solver import solve_emit



def emit(schema, table, per, cmds, cols, fkmap, colsmap, enums, unique_cols, checks=None, cuniques=None, relchecks=None, compfks=None):
    S = _seed_plan(schema, table, per, cmds, cols, fkmap, colsmap, enums, unique_cols, checks, cuniques, relchecks, compfks)
    q = S["q"]; cls = f"test_{table}"
    seed = S["seed"]; total_rows = S["total_rows"]; insert_plan = S["insert_plan"]
    nobody_ins = S["nobody_ins"]; primary = S["primary"]; pkind = S["pkind"]
    rowlinked = S["rowlinked"]; fill = S["fill"]; foreign_val = S["foreign_val"]

    out = [f"""-- GENERATED by testgen.rls (command-aware, deep-seeding) from {q}. Do not edit.
{_PGTAP_ENSURE}
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {schema} TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {schema} TO authenticated;
GRANT SELECT ON ALL TABLES IN SCHEMA {schema} TO anon;
DROP SCHEMA IF EXISTS {cls} CASCADE;
CREATE SCHEMA {cls};
CREATE FUNCTION {cls}._seed() RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  SET LOCAL ROLE service_role;
  DELETE FROM {q};
{seed}
END $$;
"""]
    n = [0]
    def fn(name, decl, actsql, cj, asserts, role="authenticated"):
        n[0] += 1
        a = "\n".join(f"  RETURN NEXT {x};" for x in asserts)
        return f"""CREATE FUNCTION {cls}.test_{n[0]:02d}_{name}() RETURNS SETOF TEXT LANGUAGE plpgsql AS $$
DECLARE runner text := current_user; {decl}
BEGIN
  PERFORM {cls}._seed();
  PERFORM set_config('request.jwt.claims', '{cj}', true);
  SET LOCAL ROLE {role};
{actsql}
  EXECUTE format('SET LOCAL ROLE %I', runner);
{a}
END $$;
"""
    cj = lambda c: json.dumps(c["claims"])
    NB = json.dumps({"sub": NOBODY, "role": "authenticated", "exp": FUTURE_EXP})

    for cmd in cmds:
        pc = per[cmd]; classes = [c for c in pc["classes"] if c["handled"]]
        if cmd == "SELECT":
            for c in classes:
                exp = total_rows if not c["rowlinked"] else 1
                out.append(fn(f"select_b{c['idx']}", "k int;", f"  SELECT count(*) INTO k FROM {q};", cj(c),
                              [f"is(k, {exp}, 'SELECT branch {c['idx']}: {'sees all (open/grant)' if not c['rowlinked'] else 'sees only its own row'}')"]))
            anon_exp = total_rows if pc.get("anon_open") else 0
            out.append(fn("select_anon", "k int;", f"  SELECT count(*) INTO k FROM {q};", "",
                          [f"is(k, {anon_exp}, 'SELECT: anon sees {('all (public policy)' if pc.get('anon_open') else 'nothing')}')"], role="anon"))
            if not pc["open"] and classes:
                out.append(fn("select_nobody_denied", "k int;", f"  SELECT count(*) INTO k FROM {q};", NB, ["is(k, 0, 'SELECT: unauthorized sees nothing')"]))
        elif cmd == "INSERT":
            for c in classes:
                if c["idx"] in insert_plan:
                    icl, iv = insert_plan[c["idx"]]
                    out.append(fn(f"insert_b{c['idx']}_ok", "got text;", f"  BEGIN INSERT INTO {q}({', '.join(iv)}) VALUES ({', '.join(iv.values())}); got:='OK'; EXCEPTION WHEN others THEN got:=SQLSTATE; END;", icl,
                                  [f"is(got, 'OK', 'INSERT branch {c['idx']}: authorized may write')"]))
            if not pc["open"] and nobody_ins:
                out.append(fn("insert_nobody_denied", "got text;", f"  BEGIN INSERT INTO {q}({', '.join(nobody_ins)}) VALUES ({', '.join(nobody_ins.values())}); got:='NO ERROR'; EXCEPTION WHEN insufficient_privilege THEN got:=SQLSTATE; WHEN others THEN got:=SQLSTATE; END;", NB,
                              ["is(got, '42501', 'INSERT: unauthorized cannot write')"]))
        elif cmd == "UPDATE" and (upd := next(((nn0, tt0) for (nn0, tt0, c0, h0) in cols if nn0 not in {x for cc in rowlinked for x in cc['rowseed']} and not h0), None)):
            for c in classes:
                out.append(fn(f"update_b{c['idx']}_ok", "m int;", f"  UPDATE {q} SET {upd[0]}={fill(upd[1])}; GET DIAGNOSTICS m=ROW_COUNT;", cj(c),
                              [f"cmp_ok(m, '>=', 1, 'UPDATE branch {c['idx']}: authorized may update its rows')"]))
                if c["rowlinked"] and c["scalar_link"] and c["fk_val"] and c["scalar_link"] not in unique_cols:
                    out.append(fn(f"update_b{c['idx']}_reassign_denied", "got text;", f"  BEGIN UPDATE {q} SET {c['scalar_link']}='{FOREIGN}'; got:='NO ERROR'; EXCEPTION WHEN insufficient_privilege THEN got:=SQLSTATE; WHEN others THEN got:=SQLSTATE; END;", cj(c),
                                  [f"is(got, '42501', 'UPDATE branch {c['idx']}: cannot move row out of scope')"]))
            if classes:
                out.append(fn("update_nobody_denied", "m int;", f"  UPDATE {q} SET {upd[0]}={fill(upd[1])}; GET DIAGNOSTICS m=ROW_COUNT;", NB, ["is(m, 0, 'UPDATE: unauthorized affects 0 rows')"]))
        elif cmd == "DELETE":
            for c in classes:
                out.append(fn(f"delete_b{c['idx']}_ok", "m int;", f"  DELETE FROM {q}; GET DIAGNOSTICS m=ROW_COUNT;", cj(c),
                              [f"cmp_ok(m, '>=', 1, 'DELETE branch {c['idx']}: authorized may delete its rows')"]))
            if classes:
                out.append(fn("delete_nobody_denied", "m int;", f"  DELETE FROM {q}; GET DIAGNOSTICS m=ROW_COUNT;", NB, ["is(m, 0, 'DELETE: unauthorized affects 0 rows')"]))
    out.append(f"\nSELECT * FROM runtests('{cls}'::name);\n")
    return "".join(out)



def emit_flat(schema, table, per, cmds, cols, fkmap, colsmap, enums, unique_cols, checks=None, cuniques=None, relchecks=None, compfks=None, helpers=True, grants_map=None, conn=None, implicit_deny=False, obs_out=None):
    """Native Supabase FLAT pgTAP form: begin; plan(N); inline AAA; finish(); rollback.

    helpers=True (DEFAULT): tests read natively — tests.create_supabase_user / authenticate_as /
      clear_authentication for identity, with tests.get_supabase_uid() substituted into the seed's
      owner columns. Custom-claim (tenant/RBAC) classes keep a direct set_config (no helper exists).
      Requires the tests.* helpers (basejump, or the rlsautotest offline shim emitted in 000-setup).
    helpers=False (--no-helpers): fully self-contained — inline set_config + SET LOCAL ROLE, ensures
      pgtap, no 000-hook dependency; one file runs standalone."""
    if conn is None:
        # F10: the old DB-less "derive" battery emitted GUESSED assertions (never probed). Removed:
        # every emitted assertion is observed against the real database first — never fabricated.
        raise ValueError("emit_flat requires a live database connection (--db-url or PG* env): "
                         "tests are probe-and-baked, not guessed")
    S = _seed_plan(schema, table, per, cmds, cols, fkmap, colsmap, enums, unique_cols, checks, cuniques, relchecks, compfks, conn=conn)
    q = S["q"]; seed = S["seed"]; total_rows = S["total_rows"]
    insert_plan = S["insert_plan"]; nobody_ins = S["nobody_ins"]; fill = S["fill"]
    rowlinked = S["rowlinked"]
    # Membership EXISTS with an internal opaque-fn conjunct (e.g. `m.room_topic = realtime.topic()`): mock the
    # fn to the seeded membership-scope value so the member row satisfies it. Prepend to `seed` so every
    # (re)seed installs it as the privileged role (wiring proof — the fn's own logic stays unverified -> footgun).
    _seed_fn_mock = False
    if conn is not None:
        _fm, _seen = [], set()
        for _cmd0 in per:
            for _c0 in per[_cmd0]["classes"]:
                for _mk0 in _c0.get("fn_mocks", []):
                    _sig0 = _opaque_fn_sig(conn, _mk0["node"])
                    if not _sig0:
                        continue
                    _st0 = (f"CREATE OR REPLACE FUNCTION {_sig0['q']}({_sig0['args']}) RETURNS {_sig0['rettype']} "
                            f"LANGUAGE sql AS $$ SELECT '{_mk0['value']}'::{_sig0['rettype']} $$")
                    if _st0 not in _seen:
                        _seen.add(_st0); _fm.append(_st0)
        if _fm:
            seed = ";\n".join(_fm) + ";\n" + seed
            _seed_fn_mock = True
    # Defect B: a logged-in identity IS a real auth.users row. In no-helpers mode the acting uid is set purely
    # via the JWT claim and is not otherwise inserted, so a trigger/FK that references auth.users (e.g. a
    # bootstrap trigger inserting a membership FK'd to auth.users) fails the probe with a foreign-key error.
    # Seed the synthetic identity subs so those resolve. ON CONFLICT keeps it idempotent; the battery is rolled back.
    if conn is not None:
        try:
            _uc = conn.cursor(); _uc.execute("SELECT to_regclass('auth.users')")
            if _uc.fetchone()[0] is not None:
                _idsubs = sorted({NOBODY, RIVAL_SUB, INS, *CV, *MV})   # INS: the fresh-identity INSERT's acting user may FK auth.users too
                seed = ";\n".join(f"INSERT INTO auth.users(id) VALUES ('{s}') ON CONFLICT DO NOTHING" for s in _idsubs) + ";\n" + seed
        except Exception:
            pass
    cj = lambda c: json.dumps(c["claims"])
    NB = json.dumps({"sub": NOBODY, "role": "authenticated", "exp": FUTURE_EXP})


    # helper-mode: create test users whose uid IS our seed uuid, so NO substitution is needed — the seed
    # stays literal and authenticate_as('u_N') returns exactly that uuid as auth.uid(). Pure-owner classes
    # (incl. owner/folder/membership/nobody) use authenticate_as; custom-claim (tenant/RBAC) keep set_config.
    body, n, sp = [], [0], [0]
    # F1/F8: the closure-captured locals now live on a typed EmitContext; the identity/description
    # helpers are its methods and the probe-then-bake discipline is the ProbeBaker (see structs/probe).
    ctx = EmitContext(schema=schema, table=table, per=per, cmds=cmds, cols=cols, fkmap=fkmap,
                      colsmap=colsmap, enums=enums, unique_cols=unique_cols, checks=checks,
                      cuniques=cuniques, relchecks=relchecks, compfks=compfks, helpers=helpers,
                      gmap=grants_map or {}, conn=conn, q=q, S=S, seed=seed, total_rows=total_rows,
                      insert_plan=insert_plan, nobody_ins=nobody_ins, fill=fill, rowlinked=rowlinked,
                      seed_fn_mock=_seed_fn_mock, NB=NB, body=body, n=n,
                      observations=(obs_out if obs_out is not None else []))
    baker = ProbeBaker(ctx)
    umap = ctx.umap
    ident = ctx.ident
    # restore the seeded precondition after a mutating test by RE-SEEDING (not SAVEPOINT/ROLLBACK):
    # real pgTAP keeps its test counter in txn-local state, and ROLLBACK TO SAVEPOINT would unwind it
    # (-> "planned N ran M" under pg_prove). Re-seeding isolates without touching the counter; the outer
    # ROLLBACK still discards everything at the end.
    seed_emit = ctx.seed_emit = _wrap_seed(seed)   # P2b: fault-tolerant arrange for the EMITTED file (raw `seed` still used for the live probe)
    # Seed as an identity-NEUTRAL privileged role: RESET ROLE drops the Postgres role but NOT the JWT claim,
    # so auth.uid() would still return the last probed identity and an ownership-on-insert trigger (e.g.
    # supabase_rbac's on_group_created) would attribute the seeded row to it. Clear the claim so auth.uid() is NULL.
    reseed = ctx.reseed = f"RESET ROLE;\nSELECT set_config('request.jwt.claims', '', true);\nDELETE FROM {q};\n{seed_emit}"
    read_test, mut_test = baker.read_test, baker.mut_test
    desc = ctx.desc
    # Real effective grants for the client roles (NOT re-granted): we PROVE actual access, never assume it.
    geff = ctx.geff
    # pick a plain writable column for the denial UPDATE (avoid identity/generated cols -> parse error before the ACL check)
    _wcol = next((nn0 for (nn0, tt0, c0, h0) in cols
                  if nn0 not in {x for cc in rowlinked for x in cc['rowseed']} and not h0),
                 (cols[0][0] if cols else None))
    ctx.deny_stmt = {"SELECT": f"SELECT 1 FROM {q}",
                     "INSERT": f"INSERT INTO {q} DEFAULT VALUES",
                     "UPDATE": (f"UPDATE {q} SET {_wcol}={_wcol}" if _wcol else None),
                     "DELETE": f"DELETE FROM {q}"}
    deny = baker.deny
    if conn is not None:   # PROBE path: observe the REAL outcome of each identity x command on the copy, then bake it
        arrange_stmts = [s for s in _split_statements(f"DELETE FROM {q};\n{seed}") if s.strip()]
        _fk_cols = set(fkmap.get(f"{schema}.{table}", {}))   # avoid FK cols: SET fk=val triggers an RI check (parent access), not the table's own UPDATE perm
        _rowseed = {x for cc in rowlinked for x in cc['rowseed']}
        # Columns referenced by ANY policy on the table (USING + WITH CHECK). SETting one of these would
        # test scope-movement or the WITH CHECK value-space, NOT the plain UPDATE grant -> exclude them so we
        # change a POLICY-NEUTRAL column. No fallback to FK/unique/policy columns (those SETs fail for reasons
        # unrelated to RLS and would mis-bake as denials); if none is neutral, upd_col stays None and UPDATE is
        # honestly "not tested - no neutral column" (surfaced as a note by the report).
        _policy_cols = set()
        try:
            # F6: read the policy ASTs, not a regex over the policy text — a column NAME inside a
            # string literal/comment no longer wrongly disqualifies a neutral column, and a quoted
            # or oddly-cased identifier can't slip past. Same demand as before: every real column
            # of THIS table referenced anywhere in any policy's USING or WITH CHECK.
            _pcur = conn.cursor()
            _pcur.execute("SELECT qual, with_check FROM pg_policies WHERE schemaname=%s AND tablename=%s", (schema, table))
            _ctypes = {nn0: tt0 for (nn0, tt0, _c, _h) in cols}
            for (_pq, _pw) in _pcur.fetchall():
                for _pe in (_pq, _pw):
                    if not _pe:
                        continue
                    _pn = _where(_pe)
                    if _pn is not None:
                        _policy_cols.update(_expr_cols(_pn, _ctypes))
        except Exception:
            _policy_cols = set()
        # A plain DEFAULT does NOT make a column unsettable — only IDENTITY / GENERATED columns can't be the
        # target of SET. (h0 = "has default OR identity" was too broad: it left ownership tables like
        # rbac.members — whose only non-key columns, roles/metadata, carry defaults — with no testable UPDATE.)
        _unsettable = set()
        try:
            _gcur = conn.cursor()
            _gcur.execute("""SELECT a.attname FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid
                JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname=%s AND c.relname=%s
                AND a.attnum>0 AND NOT a.attisdropped AND (a.attidentity <> '' OR a.attgenerated <> '')""", (schema, table))
            _unsettable = {r[0] for r in _gcur.fetchall()}
        except Exception:
            _unsettable = set()
        upd_col = next(((nn0, tt0) for (nn0, tt0, c0, h0) in cols
                        if nn0 not in _unsettable and nn0 not in _fk_cols and nn0 not in unique_cols
                        and nn0 not in _rowseed and nn0 not in _policy_cols), None)
        # No policy-neutral column at all (key-and-scope-only tables like wcard.events: PK + owner)?
        # Fall back to a SELF-ASSIGNMENT column: `SET col = col` changes nothing and moves no row
        # between scopes, but Postgres still enforces the UPDATE privilege and re-evaluates
        # USING/WITH CHECK — exactly what the UPDATE cell claims to measure. (An unchanged FK skips
        # the RI re-check, and identity/generated/unique columns are still excluded.)
        _upd_self = None if upd_col else next((nn0 for (nn0, tt0, c0, h0) in cols
                                               if nn0 not in _unsettable and nn0 not in unique_cols), None)
        ctx.arrange_stmts, ctx.fk_cols, ctx.upd_col = arrange_stmts, _fk_cols, upd_col
        _upd_val = ctx.upd_val       # CHECK-satisfying SET literal (see EmitContext.upd_val)
        pident = ctx.pident
        identities = ctx.identities  # who-labels feed the baked descriptions and the report parser
        udfs = ctx.udfs = _policy_bool_udfs(conn, schema, table)   # opaque boolean fns the policies delegate to (mock fallback)
        coltypes = ctx.coltypes = {nn0: tt0 for (nn0, tt0, c0, h0) in cols}

        _cur = conn.cursor()   # every command that HAS a policy (analyzer's cmds may omit opaque-fn ones)
        _cur.execute("SELECT DISTINCT cmd FROM pg_policies WHERE schemaname=%s AND tablename=%s", (schema, table))
        _pol = set()
        for (_cm,) in _cur.fetchall():
            _pol |= set(_CMDS4) if _cm == "ALL" else ({_cm} if _cm in _CMDS4 else set())
        for cmd in [c for c in _CMDS4 if c in (set(cmds) | _pol)]:
            _all_cls = per.get(cmd, {}).get("classes", [])
            classes = [c for c in _all_cls if c["handled"]]
            # MIXED case: a classifiable policy AND a SEPARATE opaque-function policy OR'd together (permissive).
            # The classifiable branch is probed below; without this the function branch would be left shadowed
            # (NOT_TESTABLE, untested). Mock-wire it too so the function branch is proven to grant/deny, and so
            # the report flags + highlights the mocking on those cells.
            _shadowed_fn = bool(classes) and bool(udfs) and any((not cc.get("handled")) and "function" in (cc.get("reason") or "") for cc in _all_cls)
            ctx.classes = classes
            handled = False
            for _strategy in REGISTRY:   # the old if/elif dispatch ladder, now the ordered strategy registry (F1)
                _res = _strategy(ctx, baker, cmd)   # strategies guard themselves on ctx.classes; CONTINUE = additive (F5)
                if _res == HANDLED:
                    handled = True
                    break
                if _res == AUGMENT:      # wiring tests emitted; the identity battery below still runs
                    break
            if not handled and classes and _shadowed_fn:                  # mixed: also wiring-test the shadowed opaque-fn branch
                mock_emit(ctx, baker, cmd)
            if handled:
                continue
            # BL-1: a classifiable branch handled this command, but OTHER min-terms carry a novel (unclassified)
            # atom (e.g. `owner=auth.uid() OR metadata @> '...'`). Solve each unhandled branch per-min-term and
            # DB-verify it, so the novel branch is no longer silently dropped to NT. (not udfs: opaque-fn branches
            # are mock-wired above, not solved.)
            if classes and not udfs:
                for _uc in [c for c in _all_cls if not c.get("handled") and c.get("raw_atoms")]:
                    _ra = _uc["raw_atoms"]
                    solve_emit(ctx, baker, cmd, node=(_ra[0] if len(_ra) == 1 else {"BoolExpr": {"boolop": "AND_EXPR", "args": _ra}}))
            # NO CLIENT POLICY shapes this command (it is in the matrix only via non-client roles,
            # e.g. a service_role FOR ALL): no identity could ever be "authorized", so the deny IS
            # the expected behavior for the WHOLE authenticated population. Emit it under the
            # authorized row too (per-row proofs, like SELECT's), baking only an observed clean
            # deny — an unexpected grant is left to the not-authorized row's danger cell.
            if not handled and not classes and not udfs and not per.get(cmd, {}).get("classes"):
                _ncur = conn.cursor()
                _ncur.execute("""SELECT count(*) FROM pg_policies WHERE schemaname=%s AND tablename=%s
                    AND cmd IN (%s,'ALL') AND roles && ARRAY['public','authenticated','anon']::name[]""",
                              (schema, table, cmd))
                if _ncur.fetchone()[0] == 0:
                    _nwho = "authenticated, authorized (no policy for this command grants any client)"
                    if cmd == "SELECT":
                        o = _probe(conn, arrange_stmts, pident(NB, "authenticated"), "read", f"SELECT count(*) FROM {q}")
                        if not o[2] and ((o[0] == "count" and o[1] == 0) or o[0] != "count"):
                            read_test(NB, "authenticated", baker.read_assert(o, _nwho, ident="authorized"))
                    else:
                        _nact = None
                        if cmd == "INSERT" and nobody_ins:
                            _nact = f"INSERT INTO {q}({', '.join(nobody_ins)}) VALUES ({', '.join(nobody_ins.values())})"
                        elif cmd == "UPDATE" and upd_col:
                            _nact = f"UPDATE {q} SET {upd_col[0]}={_upd_val(upd_col[0], upd_col[1])}"
                        elif cmd == "DELETE":
                            _nact = f"DELETE FROM {q}"
                        _nact = _nact or (ctx.deny_stmt or {}).get(cmd)
                        if _nact:
                            o = _probe(conn, arrange_stmts, pident(NB, "authenticated"), "write", _nact)
                            _deny = (o[0] == "err" and o[1] == "42501") or (o[0] == "rows" and o[1] == 0)
                            if not o[2] and _deny:
                                mut_test(NB, "authenticated", baker.write_assert(o, cmd, _nact, _nwho, ident="authorized"))
            for who, cjson, role, c in identities(classes):
                _oid = role if role in ("anon", "service_role") else ("authorized" if c is not None else "other")
                _wcj = cjson   # the identity that performs the WRITE (a fresh identity for unique-owner INSERTs)
                if cmd == "SELECT":
                    o = _probe(conn, arrange_stmts, pident(cjson, role), "read", f"SELECT count(*) FROM {q}")
                    read_test(cjson, role, baker.read_assert(o, who, mock_suffix=(' [mocked; wiring]' if _seed_fn_mock else ''), ident=_oid, mocked=_seed_fn_mock))
                    continue
                if cmd == "INSERT":
                    if role == "service_role":
                        # service_role INSERTs actually LAND (RLS bypass / USING true), so reusing an
                        # identity row would collide with the seed (23505 — the probe's own value, not
                        # a policy result). Build a fresh collision-free row with the synthesizer; if
                        # no clean single-statement row exists, leave the cell to the grants inference.
                        _svc_recipe, _svc_row, _svc_setup = _synthesize_row(conn, schema, table)
                        if _svc_recipe is None or not _svc_row or _svc_setup:
                            continue
                        icols = _svc_row
                    elif c is not None and c["idx"] in insert_plan:
                        # The insert plan carries ITS OWN claims: when the owner/link column is
                        # unique/PK the inserted row must belong to a FRESH identity (INS), and a
                        # WITH CHECK like (auth.uid() = id) only passes when the ACTING identity is
                        # that same fresh user. Probing with the class's claims baked a
                        # wrong-direction 'denied' here (caught on rlsautogen_demo public.profiles).
                        _wcj, icols = insert_plan[c["idx"]]
                    else:
                        icols = nobody_ins
                    if not icols:
                        # No identity-linked insert row exists (nothing rowlinked gave the seeder a
                        # shape), but for a DENY-expected identity the values are irrelevant — the
                        # denial is still testable. Probe a bare INSERT and bake ONLY a cleanly
                        # observed 42501; any other outcome keeps the honest dash.
                        _dstmt = (ctx.deny_stmt or {}).get("INSERT")
                        if _dstmt and c is None:
                            o = _probe(conn, arrange_stmts, pident(cjson, role), "write", _dstmt)
                            if not o[2] and o[0] == "err" and o[1] == "42501":
                                mut_test(cjson, role, baker.write_assert(o, cmd, _dstmt, who, ident=_oid))
                        continue
                    action = f"INSERT INTO {q}({', '.join(icols)}) VALUES ({', '.join(icols.values())})"
                elif cmd == "UPDATE":
                    # SET <plain non-FK col> = <literal>: needs ONLY the UPDATE privilege (a literal RHS
                    # avoids the SELECT-on-read requirement of `col=col`), and a non-FK col avoids an RI
                    # false-denial. upd_col already excludes FK/identity/handled cols.
                    if upd_col:
                        action = f"UPDATE {q} SET {upd_col[0]}={_upd_val(upd_col[0], upd_col[1])}"
                    elif _upd_self:
                        # self-assignment fallback (no neutral column exists): permission + policy
                        # re-check with an unchanged row — the probe observes the real outcome.
                        action = f"UPDATE {q} SET {_upd_self}={_upd_self}"
                    else:
                        continue
                else:
                    action = f"DELETE FROM {q}"
                o = _probe(conn, arrange_stmts, pident(_wcj, role), "write", action)
                # sqlstate triage (42501 vs constraint vs UNRELIABLE) lives in ProbeBaker.write_assert.
                mut_test(_wcj, role, baker.write_assert(o, cmd, action, who, ident=_oid, mocked=_seed_fn_mock))
                # TRANSITION AUDIT (cross-policy WITH CHECK leak): an authorized identity that CAN update
                # should only be able to write the column-values ITS OWN policy's WITH CHECK permits. Postgres
                # OR-combines every permissive policy's WITH CHECK independently of which USING matched, so an
                # identity can often write a value only a DIFFERENT policy intended. Enumerate the (enum) domain,
                # observe which forbidden values are actually accepted, and bake a failing assertion for each.
                if cmd == "UPDATE" and c is not None and c.get("src_check"):   # run the value-space audit regardless of the neutral-column probe (which can fail when the combined WITH CHECK excludes the seeded status)
                    _vc = _check_value_set(c["src_check"])
                    if _vc:
                        _vcol, _allowed = _vc
                        _ctype = coltypes.get(_vcol)
                        _dom = (enums.get(_ctype) or enums.get((_ctype or "").split(".")[-1])) if _ctype else None
                        if _dom and _vcol != (upd_col[0] if upd_col else None):
                            for _V in _dom:
                                if _V in _allowed:
                                    continue
                                _tact = f"UPDATE {q} SET {_vcol}='{_V}'::{_ctype}"
                                _ov = _probe(conn, arrange_stmts, pident(cjson, role), "write", _tact)
                                if _ov[0] == "rows" and _ov[1] >= 1 and not _ov[2]:   # accepted a value its own policy forbids -> leak (skip if precondition was unreliable)
                                    ctx.observations.append(Observation(cmd="UPDATE", ident=_oid, exp=False, kind="leak"))
                                    mut_test(cjson, role, f"SELECT throws_ok( $$ {_tact} $$, '42501', NULL, {desc('UPDATE: ' + who + ' can set ' + _vcol + '=' + _V + ', but policy [' + str(c.get('src_policy')) + '] WITH CHECK permits only {' + ', '.join(sorted(_allowed)) + '} -- cross-policy WITH CHECK leak [transition-leak]')} );")

        # IMPLICIT-DENY (DEFAULT; disable with --no-implicit-deny): RLS is ON and these commands have NO policy -> deny-by-default.
        # Probe each client identity and bake the OBSERVED deny so the FULL command matrix is governed in CI: a
        # future too-broad GRANT or policy that lets a no-policy command through then turns this test red.
        # Probe-and-bake (sound): only a cleanly-observed deny is baked; an unreliable seed or a non-RLS
        # constraint error (our own malformed action) is skipped, never asserted.
        if implicit_deny:
            for cmd in [c for c in _CMDS4 if c not in (set(cmds) | _pol)]:
                for who, role, cj0 in [("authenticated, no policy", "authenticated", NB), ("anon, no policy", "anon", "")]:
                    _iid = "anon" if role == "anon" else "authorized"
                    if cmd == "SELECT":
                        o = _probe(conn, arrange_stmts, pident(cj0, role), "read", f"SELECT count(*) FROM {q}")
                        if o[2]:
                            continue
                        if o[0] == "count":
                            _a = f"SELECT is( (SELECT count(*) FROM {q})::int, {o[1]}, {desc('SELECT: ' + who + ' (implicit deny) sees ' + str(o[1]) + ' row(s)')} );"
                        else:
                            _a = f"SELECT throws_ok( $$ SELECT 1 FROM {q} $$, '{o[1]}', NULL, {desc('SELECT: ' + who + ' (implicit deny) denied (' + o[1] + ')')} );"
                        ctx.observations.append(Observation(cmd=cmd, ident=_iid, exp=(o[0] == "count" and o[1] >= 1)))
                        read_test(cj0, role, _a)
                        continue
                    if cmd == "INSERT":
                        if not nobody_ins:
                            continue
                        action = f"INSERT INTO {q}({', '.join(nobody_ins)}) VALUES ({', '.join(nobody_ins.values())})"
                    elif cmd == "UPDATE":
                        if not upd_col:
                            continue
                        action = f"UPDATE {q} SET {upd_col[0]}={_upd_val(upd_col[0], upd_col[1])}"
                    else:
                        action = f"DELETE FROM {q}"
                    o = _probe(conn, arrange_stmts, pident(cj0, role), "write", action)
                    if o[2] or (o[0] == "err" and o[1] != "42501"):
                        continue   # unreliable seed, or our own action raised a non-RLS constraint error -> don't bake
                    ctx.observations.append(Observation(cmd=cmd, ident=_iid, exp=False))
                    if o[0] == "err":
                        mut_test(cj0, role, f"SELECT throws_ok( $$ {action} $$, '{o[1]}', NULL, {desc(cmd + ': ' + who + ' (implicit deny) denied (' + o[1] + ')')} );")
                    elif o[0] == "rows" and o[1] >= 1:
                        mut_test(cj0, role, f"SELECT is_empty( $$ {action} RETURNING 1 $$, {desc(cmd + ': ' + who + ' (implicit deny) must affect 0 rows — no policy means deny')} );")
                    else:
                        mut_test(cj0, role, f"SELECT is_empty( $$ {action} RETURNING 1 $$, {desc(cmd + ': ' + who + ' (implicit deny) affects 0 rows')} );")
    body_text = "\n".join(body)
    if helpers:
        creates = "\n".join(
            f"INSERT INTO auth.users (id, email, raw_user_meta_data, raw_app_meta_data, created_at, updated_at) "
            f"VALUES ('{sub}', concat('{sub}', '@test.com'), jsonb_build_object('test_identifier', '{nm}'), '{{}}'::jsonb, now(), now()) ON CONFLICT (id) DO NOTHING;"
            for sub, nm in umap.items())
        header = f"""-- GENERATED by rlsautotest (flat, helper-mode) from {q}.
-- {_TAGLINE} {_TAGLINE2}
-- Native pgTAP using the tests.* helpers (basejump or the rlsautotest offline shim in 000-setup-tests-hooks.sql).
-- Test users are created with fixed uids (= the seed uuids) so authenticate_as() lines up with the seed.
{_PGTAP_ENSURE}
BEGIN;
SELECT plan({n[0]});
-- Arrange: create test users (fixed uids), then seed as the privileged (RLS-bypassing) connection role.
-- NOTE: grants are NOT re-granted — tests run against the database's real grants so a missing grant is proven, not masked.
{creates}
SELECT public._rlsa_try($rlsa_seed$ DELETE FROM {q} $rlsa_seed$);
{seed_emit}
"""
    else:
        header = f"""-- GENERATED by rlsautotest (flat, self-contained / --no-helpers) from {q}.
-- {_TAGLINE} {_TAGLINE2}
-- Native pgTAP. Runs standalone via `supabase test db`, pg_prove, or psql. No 000-hook needed.
{_PGTAP_ENSURE}
BEGIN;
SELECT plan({n[0]});
-- Arrange: seed as the privileged (RLS-bypassing) connection role.
-- NOTE: grants are NOT re-granted — tests run against the database's real grants so a missing grant is proven, not masked.
SELECT public._rlsa_try($rlsa_seed$ DELETE FROM {q} $rlsa_seed$);
{seed_emit}
"""
    return header + "\n" + body_text + "\n\nSELECT * FROM finish();\nROLLBACK;\n"



def coverage(per, cmds):
    o = c = 0
    for cmd in cmds:
        for cl in per[cmd]["classes"]:
            for _ in ("authorized", "unauthorized"):
                o += 1
                if cl["handled"]: c += 1
    return c, o



_SHIM = r"""-- rlsautotest offline shim: basejump-API-compatible tests.* helpers, no database.dev / network.
-- Emitted only when basejump's supabase_test_helpers are NOT already installed.
CREATE SCHEMA IF NOT EXISTS tests;
GRANT USAGE ON SCHEMA tests TO anon, authenticated, service_role;
CREATE OR REPLACE FUNCTION tests.create_supabase_user(identifier text, email text DEFAULT NULL, phone text DEFAULT NULL, metadata jsonb DEFAULT NULL)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = auth, pg_temp AS $fn$
DECLARE user_id uuid;
BEGIN
  user_id := gen_random_uuid();
  INSERT INTO auth.users (id, email, phone, raw_user_meta_data, raw_app_meta_data, created_at, updated_at)
  VALUES (user_id, coalesce(email, concat(user_id, '@test.com')), phone,
          jsonb_build_object('test_identifier', identifier) || coalesce(metadata, '{}'::jsonb), '{}'::jsonb, now(), now());
  RETURN user_id;
END $fn$;
CREATE OR REPLACE FUNCTION tests.get_supabase_uid(identifier text)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = auth, pg_temp AS $fn$
DECLARE u uuid;
BEGIN
  SELECT id INTO u FROM auth.users WHERE raw_user_meta_data ->> 'test_identifier' = identifier LIMIT 1;
  IF u IS NULL THEN RAISE EXCEPTION 'User with identifier % not found', identifier; END IF;
  RETURN u;
END $fn$;
CREATE OR REPLACE FUNCTION tests.get_supabase_user(identifier text)
RETURNS json LANGUAGE plpgsql SECURITY DEFINER SET search_path = auth, pg_temp AS $fn$
DECLARE j json;
BEGIN
  SELECT json_build_object('id', id, 'email', email, 'phone', phone,
         'raw_user_meta_data', raw_user_meta_data, 'raw_app_meta_data', raw_app_meta_data) INTO j
  FROM auth.users WHERE raw_user_meta_data ->> 'test_identifier' = identifier LIMIT 1;
  IF j IS NULL OR j -> 'id' IS NULL THEN RAISE EXCEPTION 'User with identifier % not found', identifier; END IF;
  RETURN j;
END $fn$;
CREATE OR REPLACE FUNCTION tests.authenticate_as(identifier text) RETURNS void LANGUAGE plpgsql AS $fn$
DECLARE u json;
BEGIN
  u := tests.get_supabase_user(identifier);
  PERFORM set_config('role', 'authenticated', true);
  PERFORM set_config('request.jwt.claims', json_build_object('sub', u ->> 'id', 'role', 'authenticated', 'email', u ->> 'email',
          'phone', u ->> 'phone', 'user_metadata', u -> 'raw_user_meta_data', 'app_metadata', u -> 'raw_app_meta_data')::text, true);
END $fn$;
CREATE OR REPLACE FUNCTION tests.authenticate_as_service_role() RETURNS void LANGUAGE plpgsql AS $fn$
BEGIN PERFORM set_config('role', 'service_role', true); PERFORM set_config('request.jwt.claims', null, true); END $fn$;
CREATE OR REPLACE FUNCTION tests.clear_authentication() RETURNS void LANGUAGE plpgsql AS $fn$
BEGIN PERFORM set_config('role', 'anon', true); PERFORM set_config('request.jwt.claims', null, true); END $fn$;
"""



_PGTAP_ENSURE = r"""-- Make pgTAP available with ZERO setup: use the real extension if installed; otherwise load a minimal,
-- TAP-compatible shim. The shim is created ONLY when pgTAP is absent, so a real install (e.g. on Supabase)
-- is always preferred and never shadowed. Numbering uses a sequence so it survives SAVEPOINT rollbacks.
DO $rlsa$
BEGIN
  BEGIN CREATE EXTENSION IF NOT EXISTS pgtap; EXCEPTION WHEN OTHERS THEN NULL; END;
  IF to_regprocedure('plan(integer)') IS NULL THEN
    EXECUTE $b$ CREATE OR REPLACE FUNCTION public._rlsa_num() RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER AS $q$ BEGIN RETURN nextval('__rlsa_tapno'); END $q$ $b$;
    EXECUTE $b$ CREATE OR REPLACE FUNCTION public._rlsa_ok(boolean, text) RETURNS text LANGUAGE sql AS $q$ SELECT (CASE WHEN $1 THEN 'ok ' ELSE 'not ok ' END) || public._rlsa_num() || ' - ' || coalesce($2,'') $q$ $b$;
    EXECUTE $b$ CREATE OR REPLACE FUNCTION public.plan(integer) RETURNS text LANGUAGE plpgsql SECURITY DEFINER AS $q$ BEGIN EXECUTE 'DROP SEQUENCE IF EXISTS pg_temp.__rlsa_tapno'; EXECUTE 'CREATE TEMP SEQUENCE __rlsa_tapno'; RETURN '1..'||$1; END $q$ $b$;
    EXECUTE $b$ CREATE OR REPLACE FUNCTION public.finish() RETURNS SETOF text LANGUAGE plpgsql AS $q$ BEGIN RETURN; END $q$ $b$;
    EXECUTE $b$ CREATE OR REPLACE FUNCTION public.is(anyelement, anyelement, text) RETURNS text LANGUAGE sql AS $q$ SELECT public._rlsa_ok($1 IS NOT DISTINCT FROM $2, $3) $q$ $b$;
    EXECUTE $b$ CREATE OR REPLACE FUNCTION public.lives_ok(text, text) RETURNS text LANGUAGE plpgsql AS $q$ BEGIN EXECUTE $1; RETURN public._rlsa_ok(true, $2); EXCEPTION WHEN OTHERS THEN RETURN public._rlsa_ok(false, $2); END $q$ $b$;
    EXECUTE $b$ CREATE OR REPLACE FUNCTION public.throws_ok(text, text, text, text) RETURNS text LANGUAGE plpgsql AS $q$ BEGIN EXECUTE $1; RETURN public._rlsa_ok(false, $4); EXCEPTION WHEN OTHERS THEN RETURN public._rlsa_ok(SQLSTATE = $2, $4); END $q$ $b$;
    EXECUTE $b$ CREATE OR REPLACE FUNCTION public.is_empty(text, text) RETURNS text LANGUAGE plpgsql AS $q$ DECLARE r record; f boolean := false; BEGIN FOR r IN EXECUTE $1 LOOP f := true; EXIT; END LOOP; RETURN public._rlsa_ok(NOT f, $2); END $q$ $b$;
    EXECUTE $b$ CREATE OR REPLACE FUNCTION public.isnt_empty(text, text) RETURNS text LANGUAGE plpgsql AS $q$ DECLARE r record; f boolean := false; BEGIN FOR r IN EXECUTE $1 LOOP f := true; EXIT; END LOOP; RETURN public._rlsa_ok(f, $2); END $q$ $b$;
    EXECUTE $b$ CREATE OR REPLACE FUNCTION public.fail(text) RETURNS text LANGUAGE sql AS $q$ SELECT public._rlsa_ok(false, $1) $q$ $b$;
  END IF;
END
$rlsa$;
-- Seed-swallow helper: runs an arrange statement and SWALLOWS any error (in its own subtransaction) so a
-- failing seed for a genuinely un-seedable table does NOT abort the whole pgTAP file -> the table stays empty
-- and the baked UNRELIABLE assertion still runs and prints a clean `not ok` line (instead of an opaque abort).
CREATE OR REPLACE FUNCTION public._rlsa_try(sql text) RETURNS void LANGUAGE plpgsql AS $rt$ BEGIN EXECUTE sql; EXCEPTION WHEN OTHERS THEN NULL; END $rt$;"""



_HOOK_SELFTEST = (
    "\n-- Make this setup hook a VALID, trivially-passing pgTAP test. Runners that execute every .sql\n"
    "-- file in the folder (pg_prove, `supabase test db`) would otherwise report 'No plan found in TAP\n"
    "-- output' for a hook that emits no assertions and fail the whole run. The setup above runs OUTSIDE\n"
    "-- any transaction so it persists for the test files that follow; only this one assertion is the test.\n"
    "SELECT plan(1);\n"
    "SELECT is(1, 1, 'rlsautotest setup hook loaded');\n"
    "SELECT * FROM finish();\n")



def setup_hook_sql(basejump_present):
    """000-setup-tests-hooks.sql content: pgtap + (offline shim iff basejump absent) + a self-test pass."""
    head = ("-- GENERATED by rlsautotest. Pre-test hook (runs first, alphabetically).\n"
            f"-- {_TAGLINE} {_TAGLINE2}\n" + _PGTAP_ENSURE + "\n")
    if basejump_present:
        return head + "-- basejump supabase_test_helpers detected; using them.\n" + _HOOK_SELFTEST
    return head + "\n" + _SHIM + _HOOK_SELFTEST




def _load_ctx(cur, schema, table):
    pols, per, cmds, notes = analyze(cur, schema, table)
    cols = _columns(cur, schema, table)
    fkmap, colsmap = {}, {}
    def load(tbl):
        if tbl in colsmap: return
        s2, t2 = _sq(tbl); colsmap[tbl] = _columns(cur, s2, t2)
        cur.execute(_FK_SQL, (s2, t2))
        fks = {col: (f"{ps}.{pt}", pc) for (col, ps, pt, pc) in cur.fetchall()}
        fkmap[tbl] = fks
        for parent, _pc in fks.values(): load(parent)
    load(f"{schema}.{table}")
    for cmd in cmds:
        for c in per[cmd]["classes"]:
            for au in c["aux"]: load(au["table"])
    cur.execute("SELECT n.nspname, t.typname, array_agg(e.enumlabel ORDER BY e.enumsortorder) FROM pg_type t JOIN pg_enum e ON e.enumtypid=t.oid JOIN pg_namespace n ON n.oid=t.typnamespace GROUP BY 1, 2")
    enums = {}
    for nsp, tn, labels in cur.fetchall():
        enums[tn] = labels; enums[f"{nsp}.{tn}"] = labels   # key by both bare and schema-qualified name (format_type may qualify)
    cur.execute("""SELECT a.attname FROM pg_index i JOIN pg_class c ON c.oid=i.indrelid JOIN pg_namespace n ON n.oid=c.relnamespace
        JOIN pg_attribute a ON a.attrelid=i.indrelid AND a.attnum=ANY(i.indkey)
        WHERE n.nspname=%s AND c.relname=%s AND i.indisunique AND array_length(i.indkey,1)=1""", (schema, table))
    unique_cols = {r[0] for r in cur.fetchall()}
    for tbl in list(colsmap):   # load composite-FK parents (single-col parents are already loaded by load())
        s2, t2 = _sq(tbl)
        for cf in _constraint_meta(cur, s2, t2)[3]:
            load(cf["parent"])
    checks, cuniques, relchecks, compfks = {}, {}, {}, {}   # per-table constraint metadata for seeding
    for tbl in list(colsmap):
        s2, t2 = _sq(tbl); ck, cu, rc, cf = _constraint_meta(cur, s2, t2)
        if ck: checks[tbl] = ck
        if cu: cuniques[tbl] = cu
        if rc: relchecks[tbl] = rc
        if cf: compfks[tbl] = cf
    cov, tot = coverage(per, cmds)
    grants = _effective_grants(cur, schema, table)
    return dict(per=per, cmds=cmds, notes=notes, cols=cols, fkmap=fkmap, colsmap=colsmap,
                enums=enums, unique_cols=unique_cols, cov=cov, tot=tot, grants=grants,
                checks=checks, cuniques=cuniques, relchecks=relchecks, compfks=compfks)



def _emit_both(schema, table, ctx, helpers, conn=None, implicit_deny=True, obs_out=None, debug=False):
    """The flat probe-and-bake suite, plus (only when debug=True) the legacy nested runtests()
    artifact. F9: the nested emitter is DEMOTED — it predates the probe era (no probe, no
    transition audit, no UNRELIABLE, no solver) and is kept for explicit debugging only, so it
    stops being a hand-maintained second battery generator on every emit/report."""
    nt = "".join(f"-- FOOTGUN NOTE: {x}\n" for x in ctx["notes"])
    args = (schema, table, ctx["per"], ctx["cmds"], ctx["cols"], ctx["fkmap"], ctx["colsmap"], ctx["enums"], ctx["unique_cols"], ctx["checks"], ctx["cuniques"], ctx["relchecks"], ctx["compfks"])
    flat = nt + emit_flat(*args, helpers=helpers, grants_map=ctx.get("grants"), conn=conn, implicit_deny=implicit_deny, obs_out=obs_out)
    return flat, (nt + emit(*args)) if debug else None



def emit_rls_guard(cur, schema):
    """Schema-wide guard suite: every table reachable by anon/authenticated MUST have RLS enabled.
    Emitted as 010-rls-enabled.test.sql so a table shipped without RLS becomes a FAILING test —
    closes the 'no policy => no test => CI green' hole. Returns SQL, or None if nothing reachable."""
    reach = [t for (t, _rls, _pol) in all_tables(cur, schema) if _exposed(cur, schema, t)]
    if not reach:
        return None
    lines = ["-- GENERATED by rlsautotest. Schema-wide guard: every table reachable by anon/authenticated must have RLS enabled.",
             f"-- {_TAGLINE} {_TAGLINE2}",
             "-- A table granted to anon/authenticated but with RLS OFF fails here (it would otherwise pass CI silently).",
             _PGTAP_ENSURE, "BEGIN;", f"SELECT plan({len(reach)});"]
    for t in reach:
        lit = f"'\"{schema}\".\"{t}\"'::regclass"
        lines.append(f"SELECT is( (SELECT relrowsecurity FROM pg_class WHERE oid = {lit}), true, "
                     f"'{schema}.{t}: RLS must be enabled (table is reachable by anon/authenticated)' );")
    lines += ["SELECT * FROM finish();", "ROLLBACK;", ""]
    return "\n".join(lines)

